# Generated by Django 5.1.7 on 2025-07-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion']},
        ),
    ]
