# Generated by Django 5.1.7 on 2025-07-10 20:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_mother_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text='Descripción del producto', max_length=50, null=True),
        ),
    ]
